import type { CopyTemplateValue } from './types.js'

export const active = 'Active'
export const addToWallet = 'Add to wallet'
export const amount = 'Amount'
export const approvingRep = 'Approving REP…'
export const walletConnectionRequired = 'Connect wallet to continue.'
export const copied = 'Copied'
export const copiedAddress = 'Copied address'
export const copyFailed = 'Copy failed — select the value and copy it manually.'
export const copyUnavailable = 'Copy unavailable'
export const manualCopyValue = 'Exact value for manual copy'
export const createQuestion = 'Create Question'
export const createQuestionAction = 'Create question'
export const deployed = 'Deployed'
export const ends = 'Ends'
export const positiveAmountRequired = 'Enter an amount greater than zero.'
export const error = 'Error'
export const eth = 'ETH'
export const failed = 'Failed'
export const forked = 'Forked'
export const forkThresholdAttoRep = 'Fork Threshold'
export const hexValuePlaceholder = '0x...'
export const invalid = 'Invalid'
export const loading = 'Loading'
export const loadingWithEllipsis = 'Loading…'
export const loadingUniverseDetails = 'Loading universe details.'
export const max = 'Max'
export const noMatches = 'No matches'
export const notFound = 'Not found'
export const opening = 'Opening…'
export const openingWallet = 'Opening wallet…'
export const outcome = 'Outcome'
export const outcomeIndex = 'Outcome Index'
export const pending = 'Pending'
export const question = 'Question'
export const questionId = 'Question ID'
export const rep = 'REP'
export const required = 'required'
export const repPerEth = 'REP / ETH'
export const reputationToken = 'Reputation Token'
export const starts = 'Starts'
export const status = 'Status'
export const technicalDetails = 'Technical details'
export const unavailable = 'Unavailable'
export const universe = 'Universe'
export const balances = 'Balances'
export const prices = 'Prices'
export const weth = 'WETH'
export const zeroDecimalPlaceholder = '0.0'
export const connectWallet = 'Connect wallet'
export const close = 'Close'
export const deploy = 'Deploy'
export const goToGenesisUniverse = 'Go to Genesis universe'
export const zoltar = 'Zoltar'
export const none = 'None'
export const retry = 'Retry'
export const retrying = 'Retrying…'
export const formatLabelValue = (label: CopyTemplateValue, value: CopyTemplateValue) => `${label}: ${value}`
export const formatPairSlash = (leftValue: CopyTemplateValue, rightValue: CopyTemplateValue) => `${leftValue} / ${rightValue}`
export const dismissErrorActionLabel = 'Dismiss error'
export const dropdownOptions = 'Dropdown options'
export const formatCopyAddressValue = (address: CopyTemplateValue) => `Copy address ${address}`
export const formatCopyIdentifierValue = (identifier: CopyTemplateValue) => `Copy identifier ${identifier}`
export const metricUnavailablePlaceholder = '—'
export const loadMore = 'Show more'
export const nextPage = 'Next page'
export const previousPage = 'Previous page'
export const formatDecimalNumberRequiredError = (fieldLabel: CopyTemplateValue) => `${fieldLabel} must be a decimal number.`
export const approvalAmountInvalidError = 'Approval amount must be a decimal number.'
export const approvalAmount = 'Approval amount'
export const formatApproveValue = (tokenLabel: CopyTemplateValue) => `Approve ${tokenLabel}`
export const approvalSatisfied = 'Approval Satisfied'
export const formatApproveMaxValue = (tokenLabel: CopyTemplateValue) => `Approve Max ${tokenLabel}`
export const formatApproveTokenAmount = (amountLabel: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `Approve ${amountLabel}\u00a0${tokenSymbol}`
export const formatRequiredValue = (amount: CopyTemplateValue) => `Required ${amount}`
export const formatApprovedValue = (amount: CopyTemplateValue) => `Approved ${amount}`
export const formatValueApprovalAmount = (tokenLabel: CopyTemplateValue) => `${tokenLabel} Approval Amount`
export const leaveBlankForRequiredTotal = 'Leave blank for required total'
export const unlimitedApproval = 'Unlimited approval'
export const moreInfo = 'More info'
export const formatActionDetailLabel = (actionLabel: CopyTemplateValue) => `${actionLabel} details`
export const notDeployed = 'Not deployed'
export const mainnetRequiredReason = 'Switch to Ethereum mainnet.'
export const formatNetworkRequiredReason = (networkName: CopyTemplateValue) => `Switch to ${networkName}.`
export const walletAssetAutomaticImportUnavailable = 'Automatic import unavailable. Copy the token address to import it manually.'
export const walletAssetRequestAccepted = 'Request accepted'
export const walletAssetRequestFailed = 'Unable to send the token request to your wallet. Try again.'
export const walletAssetUnavailable = 'Wallet import is unavailable. Copy the token address to import it manually.'
export const formatAddTokenToWallet = (tokenLabel: CopyTemplateValue) => `Add ${tokenLabel} to wallet`
export const formatOpeningWalletForToken = (tokenLabel: CopyTemplateValue) => `Opening wallet to add ${tokenLabel}`
export const formatRetryWalletAssetRequest = (tokenLabel: CopyTemplateValue) => `Retry adding ${tokenLabel} to wallet`
export const formatWalletAssetRequestAccepted = (tokenLabel: CopyTemplateValue) => `${tokenLabel} wallet request accepted`
export const answerUnit = 'Answer Unit'
export const created = 'Created'
export const currentValue = 'Current Value'
export const displayRange = 'Display Range'
export const endTime = 'End Time'
export const maxValue = 'Max Value'
export const minValue = 'Min Value'
export const or = 'or'
export const outcomes = 'Outcomes'
export const questionDetailsLoadingLabel = 'Loading question details…'
export const questionTimeline = 'Question timeline'
export const questionType = 'Question Type'
export const selectedOutcome = 'Selected Outcome'
export const selectedTick = 'Selected Tick'
export const scalarValue = 'Scalar Value'
export const scalarValueHelpText = 'Enter a value on an increment.'
export const scalarValueInvalid = 'Enter a value between the minimum and maximum that falls on an increment.'
export const ticks = 'Ticks'
export const untitledQuestion = 'Untitled question'
