import type { CopyTemplateValue } from './types.js'

export const deleteSave = 'Delete save'
export const deletingSave = 'Deleting…'
export const exportingState = 'Exporting…'
export const importingState = 'Importing…'
export const jsonState = 'JSON state'
export const removeCorruptedSaves = 'Remove corrupted saves'
export const corruptedSavesEmptyError = 'No corrupted saved simulation states were found.'
export const formatMissingSavedStateError = (stateName: CopyTemplateValue) => `Saved simulation state "${stateName}" no longer exists.`
export const savedStateUpdateError = 'Failed to update the saved simulation state.'
export const simulationControlError = 'Failed to update the simulation.'
export const stateExportError = 'Failed to export the current simulation state.'
export const plus1Hour = '+1 hour'
export const plus1Day = '+1 day'
export const plus1Week = '+1 week'
export const plus1Month = '+1 month'
export const plus1Year = '+1 year'
export const formatQaAccountNumber = (accountIndex: CopyTemplateValue) => `QA account ${accountIndex}`
export const ready = 'Ready'
export const bootstrapping = 'Bootstrapping'
export const formatSavedStateDetail = (stateName: CopyTemplateValue, scenarioLabel: CopyTemplateValue, savedAt: CopyTemplateValue) => `Custom state "${stateName}" based on ${scenarioLabel}. Saved ${savedAt}.`
export const browserSimulation = 'Browser Simulation'
export const showSimulationDetails = 'Show details'
export const hideSimulationDetails = 'Hide details'
export const scenario = 'Scenario'
export const scenarioPreparationDetail = 'Preparing the selected simulation scenario in the background.'
export const simulationScenario = 'Simulation scenario'
export const builtInScenarios = 'Built-in scenarios'
export const savedStates = 'Saved states'
export const qaAccount = 'QA account'
export const simulationQaAccount = 'Simulation QA account'
export const blocks = 'Blocks'
export const transactions = 'Transactions'
export const blockchainTime = 'Blockchain time'
export const qaControlsPricesAndTimeTravel = 'QA controls, prices, and time travel'
export const queryDelayMs = 'Query delay (ms)'
export const repEthMockPrice = 'REP / ETH mock price'
export const repUsdcMockPrice = 'REP / USDC mock price'
export const transactionReceiptDelayMs = 'Transaction receipt delay (ms)'
export const simulationControlHelpText = 'Query delay slows simulation reads. The REP / ETH and REP / USDC mocks apply to every REP token in simulation mode. Transaction delay slows receipt confirmation so loading states stay visible.'
export const actions = 'Actions'
export const resetScenario = 'Reset scenario'
export const mineBlock = 'Mine block'
export const mint1MillionRep = 'Mint 1 million REP'
export const saveState = 'Save state'
export const exportState = 'Export state'
export const importState = 'Import state'
export const timeTravel = 'Time travel'
export const saveSimulationState = 'Save Simulation State'
export const stateName = 'State name'
export const save = 'Save'
export const savingState = 'Saving…'
export const exportSimulationState = 'Export Simulation State'
export const exportName = 'Export name'
export const refreshExport = 'Refresh export'
export const copyJson = 'Copy JSON'
export const importSimulationState = 'Import Simulation State'
export const importAndLoad = 'Import'
export const deleteSavedSimulationState = 'Delete Saved Simulation State'
export const formatDeleteSavedSimulationStateDetail = (stateName: CopyTemplateValue) => `Delete the saved state "${stateName}" from browser storage. Built-in scenarios are not affected.`
export const builtInScenarioDeletionReason = 'Built-in scenarios cannot be deleted.'
export const removeCorruptedSavedStatesTitle = 'Remove Corrupted Saved States'
export const invalidSavedStateCleanupHint = 'Remove saved simulation state entries that are no longer readable from browser storage. Valid saved states will be kept.'
