export const transactionReview = 'Transaction Review'
export const risksAndConsequences = 'Risks and Consequences'
export const youPay = 'You Pay'
export const resultingEthBalance = 'Resulting ETH Balance'
export const amountUnavailable = 'Enter a valid amount to preview'
