import type { CopyTemplateValue } from './types.js'

export const pool = 'Pool'
export const undefinedValue = 'undefined'
export const nullValue = 'null'
export const circularValue = '[circular value]'
export const contract = 'Contract'
export const to = 'To'
export const functionLabel = 'Function'
export const ethValue = 'ETH Value'
export const argumentListLabel = 'Arguments'
export const formatDeployingValue = (contractLabel: CopyTemplateValue) => `Deploying ${contractLabel}`
export const formatValueDeployed = (contractLabel: CopyTemplateValue) => `${contractLabel} Deployed`
export const simulationSubmissionDetail = 'Submitting in browser simulation. No wallet confirmation is required.'
export const walletConfirmationInstruction = 'Confirm the transaction in your wallet.'
export const walletConfirmationReviewDetail = 'Review the prepared transaction, then confirm it in your wallet.'
export const simulationSubmissionReviewDetail = 'Review the prepared transaction before it is submitted.'
export const creatingQuestion = 'Creating Question'
export const questionCreated = 'Question Created'
export const approvingForkRep = 'Approving Fork REP'
export const forkingZoltar = 'Forking Universe'
export const forkRepApproved = 'Fork REP Approved'
export const zoltarForkSubmitted = 'Universe Fork Submitted'
export const deployingChildUniverse = 'Deploying Child Universe'
export const childUniverseDeployed = 'Child Universe Deployed'
export const preparingRep = 'Preparing REP'
export const splittingRep = 'Splitting REP'
export const migrationRepPreparationSuccessDetail = 'REP was added to your migration balance.'
export const repSplitSuccessDetail = 'Migration REP was split across the selected child universes.'
export const outcomeIndexes = 'Outcome Indexes'
export const repPrepared = 'REP Prepared'
export const repSplit = 'REP Split'
export const viewTransaction = 'View transaction'
export const viewTransactionDetails = 'View transaction details'
export const preparing = 'Preparing'
export const awaitingWallet = 'Awaiting Wallet'
export const confirmed = 'Confirmed'
export const attention = 'Attention'
export const dismiss = 'Dismiss'
export const closeStatus = 'Close transaction status'
