import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'

export const applicationTitle = 'Zoltar'
export const forkZoltar = 'Fork Universe'
export const migrateRep = 'Migrate REP'
export const splitRep = 'Split REP'
export const migrationAmountAlreadySplitDetail = 'This amount is already fully split across the selected universes.'
export const alreadyForkedReason = 'This universe has already forked.'
export const formatAddMigrationRepDetail = (attoRepAmount: CopyTemplateValue) => `Splitting will automatically prepare ${attoRepAmount}\u00a0REP from your wallet.`
export const forkQuestionRequiredReason = 'Select a valid fork question to continue.'
export const forkQuestionIdInvalid = 'Enter a valid hexadecimal question ID.'
export const forkQuestionTimeLoadingReason = 'Loading current chain time before checking whether the selected question has ended.'
export const formatForkQuestionActiveReason = (endTime: CopyTemplateValue, relativeEndTime: CopyTemplateValue) => `The selected question must end before the universe can fork. It ends ${endTime} (${relativeEndTime}).`
export const forkEconomicsUnavailableReason = 'Fork burn and migration-credit terms are unavailable.'
export const forkRepInsufficientReason = 'Insufficient REP to meet the fork threshold.'
export const forkRepApprovalRequiredReason = 'Approve enough REP to continue.'
export const forkingActionLabel = 'forking the universe'
export const forkRepApprovalPending = 'Approving REP threshold…'
export const forkQuestionId = 'Fork Question ID'
export const forkSubmissionPending = 'Forking universe…'
export const addAnotherUniverse = 'Add another universe'
export const outcomeUniverses = 'Outcome Universes'
export const openUniverse = 'Open universe'
export const outcomeUniversesEmpty = 'No outcome universes available.'
export const walletBalanceLabel = 'Your balance:'
export const migratedBalanceLabel = 'Already migrated:'
export const migrationBalanceReadyDetail = 'This split uses your prepared REP.'
export const formatMigrationRepShortfall = (repShortfallAttoRep: CopyTemplateValue) => `Need ${repShortfallAttoRep}\u00a0more\u00a0REP in this universe to prepare the selected amount.`
export const migrationApprovalPendingDetail = 'Approve the wallet REP needed for this split.'
export const outcomeSelectionRequired = 'Select at least one outcome universe.'
export const outcomeBalancesLoading = 'Loading outcome universe balances…'
export const formatMigrationBalanceExceeded = (availableRep: CopyTemplateValue, migrationBalance: CopyTemplateValue, walletBalance: CopyTemplateValue) => `You only have ${availableRep}\u00a0REP available for migration in this universe (${migrationBalance} unused prepared REP and ${walletBalance}\u00a0wallet\u00a0REP).`
export const migrationRepBalance = 'Migration REP Balance'
export const migrationAmount = 'Migration Amount'
export const preparingCurrentAmountLabel = 'splitting the current amount'
export const splittingRepPending = 'Splitting REP…'
export const walletRepBalance = 'Wallet REP Balance'
export const walletRepTokens = 'Wallet REP Tokens'
export const selectedDestinations = 'Selected Destinations'
export const childUniverseRepReceived = 'Child-Universe REP Received'
export const permanentRepBurn = 'Permanent REP Burn'

export const migrationAvailableRep = 'Available to migrate'
export const migrationMaxIncludesPrepared = 'Max includes wallet REP and unused prepared REP for the selected destinations.'

export const migrationForkRequired = 'This universe must fork before REP can be split.'
export const walletRepUsed = 'Wallet REP Used'
export const migrationBalancesReadFailed = 'Could not read migration balances. Retry to continue.'
