name: zoltar-ui

services:
  zoltar:
    build:
      context: ../..
      dockerfile: ui/Dockerfile
      target: local-runtime-zoltar
    image: zoltar-ui
    ports:
      - 127.0.0.1:8012:8012
    environment:
      UI_APP: zoltar

networks:
  default:
    name: zoltar
    external: true
